name: Maven CI Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Run tests
      run: mvn clean test
    - name: Build JAR
      run: mvn clean install -DskipTests
    - name: SonarQube analysis
      env:
        SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn clean verify sonar:sonar -Dsonar.login=$SONAR_LOGIN
